# Generated by Django 5.0.6 on 2024-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Tarea')),
                ('nombreTarea', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('descripcion', models.TextField(verbose_name='Agrega una descripción')),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created'],
            },
        ),
    ]
