# Generated by Django 5.0.6 on 2024-07-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID GRUPO')),
                ('nombreGrupo', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('descripcionMateria', models.TextField(verbose_name='Agrega una descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img-materias/', verbose_name='Imagen de la materia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEvento', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('fechaEvento', models.DateField(verbose_name='Fecha del evento')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img-eventos/', verbose_name='Imagen del evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fechaEvento'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tarea')),
                ('nombreTarea', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('descripcion', models.TextField(verbose_name='Agrega una descripción')),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('imagen', models.ImageField(null=True, upload_to='img-tareas', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.grupo', verbose_name='Grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['created'],
            },
        ),
    ]
