# Generated by Django 5.0.6 on 2024-07-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_tareas_idtarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEvento', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('fechaEvento', models.DateField(verbose_name='Fecha del evento')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img-eventos/', verbose_name='Imagen del evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fechaEvento'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID GRUPO')),
                ('nombreGrupo', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='tareas',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.grupo', verbose_name='Grupo'),
        ),
    ]
