# Generated by Django 5.0.6 on 2024-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_tareas_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('descripcionMateria', models.TextField(verbose_name='Agrega una descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img-materias/', verbose_name='Imagen de la materia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['created'],
            },
        ),
    ]
