# Generated by Django 5.0.6 on 2024-07-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['created'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['created'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.grupo', verbose_name='Grupo'),
        ),
    ]
