# Generated by Django 5.0.6 on 2024-07-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_evento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.materia', verbose_name='Materia'),
        ),
    ]
