# Generated by Django 5.0.6 on 2024-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_tarea_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcionMateria',
            field=models.TextField(verbose_name='Descripción de la Materia'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img-tareas/', verbose_name='Imagen de la tarea'),
        ),
    ]
