# Generated by Django 5.0.6 on 2024-07-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_alter_materia_descripcionmateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='grupo',
        ),
    ]
