# Generated by Django 5.0.6 on 2024-07-08 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_remove_evento_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descripcionMateria',
            field=models.TextField(verbose_name='Agrega una descripción'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(verbose_name='Agrega una descripción'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img-tareas', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.materia', verbose_name='Materia'),
        ),
    ]
