# Generated by Django 5.0.6 on 2024-07-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_evento_grupo_alter_materia_descripcionmateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='grupo',
        ),
    ]
