# Generated by Django 5.0.6 on 2024-08-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_alter_evento_grupo_alter_tarea_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del padre de familia')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentario',
            },
        ),
    ]
