# Generated by Django 5.0.6 on 2024-08-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Comentario',
        ),
    ]
