# Generated by Django 5.0.6 on 2024-08-01 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_rename_contact_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
