# Generated by Django 5.0.6 on 2024-08-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_comentario_created_comentario_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='updated',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='created',
            new_name='creado',
        ),
    ]
