# Generated by Django 5.0.6 on 2024-08-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
