# Generated by Django 5.0.6 on 2024-08-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_tarea_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='grupo',
            field=models.CharField(default=1, max_length=2, verbose_name='Nombre del grupo'),
            preserve_default=False,
        ),
    ]
