# Generated by Django 5.0.6 on 2024-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0022_comentario_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='grupos',
            field=models.CharField(default=1, max_length=4, verbose_name='Nombre del grupo'),
            preserve_default=False,
        ),
    ]
