# Generated by Django 5.0.6 on 2024-08-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0023_remove_comentario_grupo_comentario_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='material',
        ),
    ]
