# Generated by Django 5.0.6 on 2024-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_alter_grupo_options_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img-eventos/', verbose_name='Imagen del evento'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaEntrega',
            field=models.DateField(null=True, verbose_name='Fecha de entrega'),
        ),
    ]
